import dotenv from "dotenv";
import postgres from "postgres";

dotenv.config({ path: ".env.local" });
dotenv.config();

const databaseUrl = process.env.DATABASE_URL;
if (!databaseUrl) {
  throw new Error("DATABASE_URL is not set (expected in .env.local)");
}

const sql = postgres(databaseUrl, {
  ssl: { rejectUnauthorized: false },
});

async function migrate() {
  await sql`CREATE TABLE IF NOT EXISTS users (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email TEXT UNIQUE,
    role TEXT CHECK(role IN ('factory', 'buyer', 'admin')),
    company_name TEXT,
    wechat_id TEXT,
    mobile_number TEXT,
    whatsapp_number TEXT,
    is_approved BOOLEAN DEFAULT FALSE
  )`;

  await sql`CREATE TABLE IF NOT EXISTS products (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT,
    description TEXT,
    specifications TEXT,
    photo TEXT,
    factory_price_cny DOUBLE PRECISION,
    buyer_price_inr DOUBLE PRECISION,
    status TEXT DEFAULT 'draft',
    factory_id INTEGER REFERENCES users(id),
    category TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
  )`;

  await sql`CREATE TABLE IF NOT EXISTS orders (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id INTEGER REFERENCES products(id),
    buyer_id INTEGER REFERENCES users(id),
    quantity INTEGER,
    status TEXT DEFAULT 'pending',
    rejection_reason TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
  )`;

  await sql`CREATE TABLE IF NOT EXISTS notifications (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES users(id),
    message TEXT NOT NULL,
    type TEXT,
    related_id INTEGER,
    is_read BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMPTZ DEFAULT NOW()
  )`;

  await sql`CREATE TABLE IF NOT EXISTS settings (
    key TEXT PRIMARY KEY,
    value TEXT
  )`;

  await sql`CREATE TABLE IF NOT EXISTS custom_orders (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    buyer_id INTEGER REFERENCES users(id),
    photo TEXT,
    requirements TEXT,
    status TEXT DEFAULT 'pending',
    created_at TIMESTAMPTZ DEFAULT NOW()
  )`;

  await sql`CREATE TABLE IF NOT EXISTS custom_order_proposals (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    custom_order_id INTEGER REFERENCES custom_orders(id),
    factory_id INTEGER REFERENCES users(id),
    photo TEXT,
    description TEXT,
    price_cny DOUBLE PRECISION,
    price_inr DOUBLE PRECISION,
    status TEXT DEFAULT 'pending',
    created_at TIMESTAMPTZ DEFAULT NOW()
  )`;

  await sql`INSERT INTO settings (key, value)
    VALUES ('exchange_rate', '12.0')
    ON CONFLICT (key) DO NOTHING`;
  await sql`INSERT INTO settings (key, value)
    VALUES ('admin_markup', '1.2')
    ON CONFLICT (key) DO NOTHING`;

  const [{ count }] = await sql<{ count: number }[]>`SELECT COUNT(*)::int as count FROM users`;
  if (count === 0) {
    await sql`INSERT INTO users (email, role) VALUES ('admin@lumina.com', 'admin')`;
    await sql`INSERT INTO users (email, role) VALUES ('factory@china.com', 'factory')`;
    await sql`INSERT INTO users (email, role) VALUES ('buyer@india.com', 'buyer')`;
  }
}

migrate()
  .then(() => {
    console.log("Database migration complete");
  })
  .catch((error) => {
    console.error("Database migration failed:", error);
    process.exitCode = 1;
  })
  .finally(async () => {
    await sql.end({ timeout: 5 });
  });
